### ISSUE TITLE
Crash learning

### ISSUE THREAD

**Issue by SirOMGitsYOU** [Kinetic-Development/Crashy-Issues#1]
[crash-2020-08-18_23.09.14-client.txt](https://github.com/Kinetic-Development/Crashy-Issues/files/5093157/crash-2020-08-18_23.09.14-client.txt)
This crash was caused by a mod on the latest version of forge being unable to locate the correct texture, Option lower forge version or wait for mod developer to update - easiest option is to remove mod as likely poorly made.

**Comment by SlumberingTea** [comment]
Thanks for the report
