### ISSUE TITLE
Arcane Seals Research for Thaumcraft 4

### ISSUE THREAD

**Issue by CuckCorn18** [Kinetic-Development/Crashy-Issues#5]
Okay, so everytime I get a research node for Arcane Seals, I crash. It says "An error has occured and the connection has been terminated." and as a result of that, I get sent back to the hub. What is causing this? I must know. Here's the crash report just in case anyone has any idea what the cause of this is.
[crash-2020-09-16_22.05.56-client.txt](https://github.com/dapper-fox-studios/Crashy-Issues/files/6446841/crash-2020-09-16_22.05.56-client.txt)

**Comment by ArcadiaBlues** [comment]
This issue occurs because Thaumic Additions is not present in the server. To prevent this issue from occurring in future, you can either use the Curseforge version of the pack, or remove Thaumic Additions from your Technic mod folder
